name: mapsindoors_mapbox_android
description: Android implementation of the mapsindoors plugin using the Mapbox platform
version: 2.1.3
repository: https://github.com/MapsPeople/mapsindoors_flutter_mapbox_android
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: mapsindoors
    platforms:
      android:
        package: com.mapspeople.mapsindoors.core
        pluginClass: MapsindoorsPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.15
  mapsindoors_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
